CONTRACT_TYPE = {
    "договороказанияуслуг": "Original",
    "посредническийдоговор": "Intermediary",
    "дополнительноесоглашение": "Additional",
    "original": "Original",
    "intermediary": "Intermediary",
    "intermediarycontract": "Intermediary",
    "additional": "Additional",
    "additionalagreement": "Additional",
    "contract": "Original",
}

SUBJECT_TYPE = {
    "договорнараспространениерекламы": "Distribution",
    "договорнаорганизациюраспространениярекламы": "DistributionOrganization",
    "посредничество": "Mediation",
    "представительство": "Representation",
    "иное": "Other",
    "другое": "Other",
    "distribution": "Distribution",
    "distributionorganization": "DistributionOrganization",
    "mediation": "Mediation",
    "representation": "Representation",
    "other": "Other",
    "orgdistribution": "DistributionOrganization",
}

ACTIVITY_TYPE = {
    "действиявцеляхраспространениярекламы": "Distribution",
    "иное": "Other",
    "заключениедоговоров": "Conclude",
    "коммерческоепредставительство": "Commercial",
    "distribution": "Distribution",
    "other": "Other",
    "conclude": "Conclude",
    "commercial": "Commercial",
    "none": "None",
    "нет": "None",
}

PARTY_TYPE = {
    "юрлицо": "LegalPerson",
    "юрлицорф": "LegalPerson",
    "юридическоелицо": "LegalPerson",
    "ul": "LegalPerson",
    "ful": "ForeignLegalPerson",
    "ffl": "ForeignPhysicalPerson",
    "fl": "PhysicalPerson",
    "residentlegal": "LegalPerson",
    "ип": "IndividualEntrepreneur",
    "ипрф": "IndividualEntrepreneur",
    "ip": "IndividualEntrepreneur",
    "индивидуальныйпредприниматель": "IndividualEntrepreneur",
    "индивидуальныйпредпринимательрф": "IndividualEntrepreneur",
    "residententrepreneur": "IndividualEntrepreneur",
    "физическоелицорф": "PhysicalPerson",
    "физлицо": "PhysicalPerson",
    "residentindividual": "PhysicalPerson",
    "иностранноеюрлицо": "ForeignLegalPerson",
    "иностранноеюридическоелицо": "ForeignLegalPerson",
    "иностранноефизлицо": "ForeignPhysicalPerson",
    "иностранноефизическоелицо": "ForeignPhysicalPerson",
    "notresidentlegal": "ForeignLegalPerson",
    "notresidentindividual": "ForeignPhysicalPerson",
    "legalperson": "LegalPerson",
    "individualentrepreneur": "IndividualEntrepreneur",
    "physicalperson": "PhysicalPerson",
    "foreignlegalperson": "ForeignLegalPerson",
    "foreignphysicalperson": "ForeignPhysicalPerson",
}

TEMPLATE_COLUMNS = {
    "erid": 1,
    "contract_no": 2,
    "contract_date": 3,
    "contract_type": 4,
    "contract_subject": 5,
    "activity_type": 6,
    "customer_type": 7,
    "customer_name": 8,
    "customer_address": 9,
    "customer_inn": 10,
    "customer_reg_no": 11,
    "customer_oksm": 12,
    "contractor_type": 13,
    "contractor_name": 14,
    "contractor_address": 15,
    "contractor_inn": 16,
    "contractor_reg_no": 17,
    "contractor_oksm": 18,
    "vat_included": 19,
    "impressions": 20,
    "amount": 21,
}

TEMPLATE_HEADERS = (
    "ERID",
    "Номер изначального договора",
    "Дата изначального договора",
    "Тип договора",
    "Предмет договора",
    "Вид деятельности",
    "Тип заказчика",
    "Заказчик",
    "Адрес заказчика",
    "ИНН заказчика или его аналог",
    "Рег.номер заказчика",
    "ОКСМ заказчика",
    "Тип исполнителя",
    "Исполнитель",
    "Адрес исполнителя",
    "ИНН исполнителя или его аналог",
    "Рег.номер исполнителя",
    "ОКСМ исполнителя",
    "Включая НДС",
    "Показы",
    "Сумма",
)

TEMPLATE_COL_COUNT = len(TEMPLATE_COLUMNS)

if len(TEMPLATE_HEADERS) != TEMPLATE_COL_COUNT:
    raise RuntimeError("TEMPLATE_HEADERS must match TEMPLATE_COLUMNS")
